#!/usr/bin/env sh

# bar settings
yabai -m config external_bar all:0:25

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  8
yabai -m config bottom_padding               5
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   06
yabai -m config window_shadow                float

# space specific settings
yabai -m config --space 1 layout float
yabai -m config --space 1 top_padding 0
yabai -m config --space 1 left_padding 0
yabai -m config --space 1 right_padding 0

yabai -m config --space 3 top_padding 0
yabai -m config --space 3 bottom_padding 0
yabai -m config --space 3 left_padding 0
yabai -m config --space 3 right_padding 0

yabai -m config --space 4 top_padding 0
yabai -m config --space 4 bottom_padding 0
yabai -m config --space 4 left_padding 0
yabai -m config --space 4 right_padding 0

yabai -m config --space 5 top_padding 0
yabai -m config --space 5 bottom_padding 0
yabai -m config --space 5 left_padding 0
yabai -m config --space 5 right_padding 0

# float these apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Font Book$" manage=off

# move these apps to space
yabai -m rule --add app="Slack"                 space=3
yabai -m rule --add app="Evernote"              space=4
yabai -m rule --add app="Messages"              space=5

echo "yabai configuration loaded.."
