#!/bin/bash
# This "docker-credential-gh" utility should exist an as executable somewhere in PATH.
#
# Dependencies: gh
#
set -e

cmd="$1"
if [ "erase" = "$cmd" ]; then
  cat - >/dev/null
  exit 0
fi
if [ "store" = "$cmd" ]; then
  cat - >/dev/null
  exit 0
fi
if [ "get" != "$cmd" ]; then
  exit 1
fi

host="$(cat -)"
host="${host#https://}"
host="${host%/}"
if [ "$host" != "ghcr.io" ] && [ "$host" != "docker.pkg.github.com" ]; then
  exit 1
fi

token="$(gh config get -h github.com oauth_token)"
if [ -z "$token" ]; then
  exit 1
fi

printf '{"Username":"%s", "Secret":"%s"}\n' "$(gh config get -h github.com user)" "$token"
