#!/bin/bash

# docker-install-ubuntu is a helper for installing the docker apt repos and the docker-ce deb on an ubuntu node.
# it's based on docker's official instructions as of 09/2017.
# allow overriding the inferred ubuntu release name

UBUNTU_RELEASE=${UBUNTU_RELEASE:-$(lsb_release -cs)}

sudo apt-get install \
  apt-transport-https \
  ca-certificates \
  curl \
  software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  "$UBUNTU_RELEASE" \
  stable edge"

sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  "$UBUNTU_RELEASE" \
  edge"

sudo apt-get update
sudo apt-get install docker-ce
