#!/bin/bash

setup_nvim() {
  echo "==> Symlinking $HOME/.neovim.init.vim -> $HOME/.config/nvim/init.vim"
  [[ ! -e "$HOME/.config/nvim" ]] && mkdir -p "$HOME/.config/nvim"
  [[ ! -e "$HOME/.config/nvim/init.vim" ]] && ln -sf "$HOME/.neovim.init.vim" "$HOME/.config/nvim/init.vim"

  if [[ ! -e "$HOME/.local/share/nvim/site/autoload/plug.vim" ]]; then
    echo "==> Installing vim-plug"
    # install vim-plug - https://github.com/junegunn/vim-plug
    curl -fLo "$HOME/.local/share/nvim/site/autoload/plug.vim" --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  tools update-nvim
}
setup_nvim "$@"
