#!/bin/bash

set -eou pipefail

[[ -n "${DEBUG:-}" ]] && set -x

SSH_CERT_FILE="${SSH_CERT_FILE:-$HOME/.ssh/planetscale}"
USER="${USER:-}"

unset SSH_AUTH_SOCK

if [[ -z "$USER" ]]; then
  echo "Must set USER env var."
  exit 1
fi

need_cert=1
if [[ -e "$SSH_CERT_FILE" ]]; then
  if ! step ssh needs-renewal "$SSH_CERT_FILE-cert.pub" >/dev/null 2>&1; then
    need_cert=0
  fi
fi

if [[ "$need_cert" = "1" ]]; then
  step ssh certificate --force --insecure --no-password --no-agent "$USER" "$SSH_CERT_FILE"
fi

case "$0" in
  *ssh*) cmd=ssh ;;
  *scp*) cmd=scp ;;
esac


exec "$cmd" -i "$SSH_CERT_FILE" -oIdentitiesOnly=yes "$@"
