## where to store your database, default is your system data directory
## mac: ~/Library/Application Support/com.elliehuxtable.atuin/history.db
## linux: ~/.local/share/atuin/history.db
# db_path = "~/.history.db"

## where to store your encryption key, default is your system data directory
# key_path = "~/.key"

## where to store your auth session token, default is your system data directory
# session_path = "~/.key"

## date format used, either "us" or "uk"
# dialect = "uk"

## enable or disable automatic sync
# auto_sync = true

## how often to sync history. note that this is only triggered when a command
## is ran, so sync intervals may well be longer
## set it to 0 to sync after every command
sync_frequency = "10m"

## address of the sync server
# sync_address = "https://api.atuin.sh"

## which search mode to use
## https://docs.atuin.sh/configuration/config/#search_mode
## Atuin supports “prefix”, “fulltext”, “fuzzy”, and “skim” search modes.
 search_mode = "skim"

 style = "compact"

 inline_height = 20


[stats]
# Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
  "cargo",
  "go",
  "git",
  "g",
  "npm",
  "yarn",
  "pnpm",
  "kubectl",
  "k",
  "ku"
]

# Set commands that should be totally stripped and ignored from stats
common_prefix = ["sudo", "_"]
