kind: SwitchConfig
version: v1alpha1
kubeconfigName: "*.kubeconfig"
refreshIndexAfter: 10m # use short ttl because all of our kubeconfigs are local. you can always clear the index by running `switch --no-index` one time
kubeconfigStores:
- kind: filesystem
  kubeconfigName: "*.kubeconfig"
  paths:
  - ~/.kube/
  - ~/.kube/config
hooks:
  - name: pskube-update-user
    type: InlineCommand
    # execution:
    #   interval: 24h
    arguments:
      - "for i in $(pskube --list); do pskube $i >/dev/null ; done "
  - name: pskube-update-ops
    type: InlineCommand
    # execution:
    #   interval: 24h
    arguments:
      - "for i in $(pskube --list); do PS_USE_OPS_ROLE=1 pskube $i >/dev/null ; done "
